<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>Lars Dytterud</Authors>
    <Copyright>Copyright (c) 2026 Lars Dytterud</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Deterministic>true</Deterministic>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)CHANGELOG.md'))</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false' And '$(MSBuildProjectName)' != 'QuickDraw.Pict.Tests'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)THIRD-PARTY-NOTICES.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
</Project>
